### ISSUE TITLE
QR scanner/camera permissions problem

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-IOS-App#6]
On Michael's iPhone SE when you go to the QR scanner, it prints "unable to access camera" to the log, and just shows a spinning/loading animation.

It looks like Kyle was using this tutorial maybe?
https://www.appcoda.com/barcode-reader-swift/

I'm sure it was working on Kyle's phone, but... why is it not working on a fresh device?  (Need to request camera permissions earlier somewhere/somehow?)

**Comment by fstonedahl** [comment]
Update: Apparently our old iPhone SE doesn't have a **builtInDualCamera**, so the DiscoverySession was failing to return any matching devices.

However, it does have a **builtInWideAngleCamera**, so that works on the iPhone SE.

We can close this issue once we confirm that other iPhone models work fine with the **builtInWideAngleCamera** also.

**Comment by mwardach** [comment]
Tested on an IPhone 7 and it worked. It looks like this will work so long as the newer IPhones haven't drastically changed anything.
